[versions]
agp = "8.7.3"
material = "1.12.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

